version: "3"

# silent: true

dotenv:
  - .env

env:
  DOCKER_COMMAND: docker # here you can set "podman", for example
  COMPOSE_MAIN_SERVICE: n8n

vars:
  OLLAMA_MODEL: deepseek-r1:1.5b

includes:
  main:
    taskfile: ./.taskfiles/docker.Taskfile.yml
    flatten: true
    dir: "{{.USER_WORKING_DIR}}"
  lint:
    taskfile: ./.taskfiles/lint.Taskfile.yml
    dir: "{{.USER_WORKING_DIR}}"

tasks:
  setup:
    aliases:
      - config
      - install
    deps: [install:deps, setup-env, pull-models]

  install:deps:
    desc: Install dependencies
    cmds:
      - echo "Installing dependencies..."
      - pnpm install

  setup-env:
    desc: Create .env file from example
    cmds:
      - cp .env.example .env
      - echo ".env file created from example"

  pull-models:
    desc: Pull recommended LLM models for Ollama
    deps:
      - up
    cmds:
      - docker compose exec ollama ollama pull {{.OLLAMA_MODEL}}

  logs:n8n:
    desc: Show logs for n8n
    cmds:
      - task: logs
        vars:
          SERVICE: "n8n"

  logs:ollama:
    desc: Show logs for ollama
    cmds:
      - task: logs
        vars:
          SERVICE: "ollama"

  logs:postgres:
    desc: Show logs for postgres
    cmds:
      - task: logs
        vars:
          SERVICE: "postgres"

  logs:qdrant:
    desc: Show logs for qdrant
    cmds:
      - task: logs
        vars:
          SERVICE: "qdrant"

  clean:data:
    desc: Remove service's data
    cmds:
      - echo "Removing service's data..."
      - rm -rf ./services/**/data/**

  clean:all:
    desc: Remove all containers, volumes and data
    cmds:
      - task: clean
      - task: clean:data

  restart:all:
    desc: Restart all services
    cmds:
      - task: clean:all
      - task: start
